// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import type { Database } from './types';

const SupabaseEnvSchema = z.object({
  VITE_SUPABASE_URL: z.string().url().optional(),
  VITE_SUPABASE_PUBLISHABLE_KEY: z.string().min(1).optional(),
  VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY: z.string().min(1).optional(),
});

const ENV_FALLBACK = {
  url: 'https://invalid.supabase.local',
  key: 'invalid-publishable-key',
} as const;

const parsedEnv = SupabaseEnvSchema.safeParse(import.meta.env);
const configuredUrl = parsedEnv.success ? parsedEnv.data.VITE_SUPABASE_URL : undefined;
const configuredKey = parsedEnv.success
  ? parsedEnv.data.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY || parsedEnv.data.VITE_SUPABASE_PUBLISHABLE_KEY
  : undefined;

export const isSupabaseConfigured = Boolean(configuredUrl && configuredKey);

if (!isSupabaseConfigured) {
  const validationDetails = parsedEnv.success
    ? 'Missing VITE_SUPABASE_URL and/or publishable key.'
    : parsedEnv.error.issues
        .map((issue) => `${issue.path.join('.')}: ${issue.message}`)
        .join('; ');

  console.error('[supabase-config] Invalid configuration; running in offline-safe mode.', {
    validationDetails,
    hasUrl: Boolean(configuredUrl),
    hasPublishableKey: Boolean(configuredKey),
  });
}

const supabaseUrl = configuredUrl ?? ENV_FALLBACK.url;
const supabasePublishableKey = configuredKey ?? ENV_FALLBACK.key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
