// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import type { Database } from './types';

const SupabaseEnvSchema = z.object({
  VITE_SUPABASE_URL: z.string().url(),
  VITE_SUPABASE_PUBLISHABLE_KEY: z.string().min(1).optional(),
  VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY: z.string().min(1).optional(),
});

const parsedEnv = SupabaseEnvSchema.safeParse(import.meta.env);

if (!parsedEnv.success) {
  throw new Error(
    `Invalid Supabase environment configuration: ${parsedEnv.error.issues
      .map((issue) => `${issue.path.join('.')}: ${issue.message}`)
      .join('; ')}`
  );
}

const SUPABASE_URL = parsedEnv.data.VITE_SUPABASE_URL;
// Support both VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY (Lovable) and VITE_SUPABASE_PUBLISHABLE_KEY (standard)
const SUPABASE_PUBLISHABLE_KEY =
  parsedEnv.data.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  parsedEnv.data.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required Supabase environment variables. ' +
    'Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY) in your .env file or platform configuration.'
  );
}

const supabaseUrl = configuredUrl ?? ENV_FALLBACK.url;
const supabasePublishableKey = configuredKey ?? ENV_FALLBACK.key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
