name: Cloudflare Pages Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: "cfat_6iNrQ0PDrjOAeeS3dEkuyPQCiEikCWtTf2KOTbX966f12af6"
          accountId: "b8a58a01bf34e1d6e46adf9765b159e8"
          command: pages deploy dist --project-name=rmp-apex
